--
-- script to create all entities in this project
-- generated by GenerateSqlCommand
-- generated at 2020-11-21T21:13:44.959987Z
--

create sequence hibernate_sequence start 1 increment 1;

    create table owners (
       id int8 not null,
        first_name varchar(255),
        last_name varchar(255),
        address varchar(255),
        city varchar(255),
        telephone varchar(255),
        primary key (id)
    );

    create table pets (
       id int8 not null,
        name varchar(255),
        birth_date date,
        owner_id int8 not null,
        type_id int8 not null,
        primary key (id)
    );

    create table specialties (
       id int8 not null,
        name varchar(255),
        primary key (id)
    );

    create table types (
       id int8 not null,
        name varchar(255),
        primary key (id)
    );

    create table vet_specialties (
       vet_id int8 not null,
        specialty_id int8 not null,
        primary key (vet_id, specialty_id)
    );

    create table vets (
       id int8 not null,
        first_name varchar(255),
        last_name varchar(255),
        primary key (id)
    );

    create table visits (
       id int8 not null,
        visit_date date,
        description varchar(255),
        pet_id int8 not null,
        primary key (id)
    );
create index owners_last_name on owners (last_name);
create index pets_name on pets (name);
create index specialties_name on specialties (name);
create index types_name on types (name);
create index vets_last_name on vets (last_name);
create index visits_pet_id on visits (pet_id);

    alter table if exists pets
       add constraint FK6teg4kcjcnjhduguft56wcfoa
       foreign key (owner_id)
       references owners;

    alter table if exists pets
       add constraint FKtmmh1tq8pah5vxf8kuqqplo4p
       foreign key (type_id)
       references types;

    alter table if exists vet_specialties
       add constraint FK35uiboyrpfn1bndrr5jorcj0m
       foreign key (specialty_id)
       references specialties;

    alter table if exists vet_specialties
       add constraint FKby1c0fbaa0byaifi63vt18sx9
       foreign key (vet_id)
       references vets;

    alter table if exists visits
       add constraint FK6jcifhlqqlsfseu67utlouauy
       foreign key (pet_id)
       references pets;
